version: "3.9"

services:
  # ==========================
  # Stockage objet S3-compatible (Bronze)
  # ==========================
  minio:
    image: minio/minio:latest
    container_name: tp-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - db_network_ecommerce

  # ==========================
  # PostgreSQL – Data Warehouse
  # ==========================
  db:
    image: postgres
    container_name: local_pgdb_ecommerce
    restart: always
    ports:
      - "5440:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: supershop
    volumes:
      - C:/Users/Administrateur/Documents/postgres_data_docker:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d
    networks:
      - db_network_ecommerce

  # ==========================
  # pgAdmin – Interface Web PostgreSQL
  # ==========================
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_gui_ecommerce
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - local_pgadmin_ecommerce:/var/lib/pgadmin
    networks:
      - db_network_ecommerce

volumes:
  minio_data:
  local_pgadmin_ecommerce:

networks:
  db_network_ecommerce:
    driver: bridge
